#!/usr/bin/env python3
"""
Regenerate crates/khadi-hud/src/globe/land.txt from the eDEX-UI clone.

The land grid is eDEX's own: src/assets/misc/grid.json, the tile set
encom-globe draws its dotted continents from. Khadi is GPL-3.0 and so is
eDEX, so this is the authentic data rather than an approximation of it.

THE lat/lon FIELDS IN grid.json ARE NOT GEOGRAPHIC. Taken at face value they
put land in the Indian Ocean and none in Antarctica. The usable position is
the tile's 3D boundary, which is a real point on a sphere of radius 500; the
geographic frame was then solved for against known land and sea coordinates:

    polar axis = Y,  lon = atan2(x, z) + 85 degrees,  not mirrored

That scores 14 of 14 on eight land and six ocean probes. Re-run with --verify
to check it again.

    python3 spike/globe-land.py            # write the data file
    python3 spike/globe-land.py --verify   # just re-check the orientation
"""
import json, math, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "edex-ui/src/assets/misc/grid.json"
OUT = ROOT / "crates/khadi-hud/src/globe/land.txt"
LON_OFFSET = 85.0

LAND = [(-5,-62,"Amazon"),(22,10,"Sahara"),(62,100,"Siberia"),(-25,134,"Australia"),
        (40,-100,"US"),(55,37,"Moscow"),(-30,25,"S.Africa"),(28,80,"India")]
SEA  = [(0,-140,"mid-Pacific"),(-20,80,"Indian Ocean"),(30,-40,"N.Atlantic"),
        (-40,-120,"S.Pacific"),(0,-25,"Eq.Atlantic"),(-50,80,"S.Indian")]


def points():
    if not SRC.is_file():
        sys.exit(f"no {SRC} — clone eDEX-UI first (see PLAN.md section 10)")
    out = []
    for tile in json.load(SRC.open())["tiles"]:
        b = tile["b"]
        n = len(b)
        x = sum(p["x"] for p in b) / n
        y = sum(p["y"] for p in b) / n
        z = sum(p["z"] for p in b) / n
        r = math.sqrt(x * x + y * y + z * z)
        lat = math.degrees(math.asin(max(-1.0, min(1.0, y / r))))
        lon = (math.degrees(math.atan2(x, z)) + LON_OFFSET + 180.0) % 360.0 - 180.0
        out.append((round(lat, 1), round(lon, 1)))
    return sorted(set(out))


def verify(pts):
    near = lambda la, lo: any(
        abs(a - la) < 7 and abs(((b - lo + 180) % 360) - 180) < 7 for a, b in pts)
    bad = [n for la, lo, n in LAND if not near(la, lo)] + \
          [n for la, lo, n in SEA if near(la, lo)]
    print(f"orientation: {len(LAND)+len(SEA)-len(bad)}/{len(LAND)+len(SEA)} probes agree")
    for n in bad:
        print(f"  WRONG: {n}")
    return not bad


if __name__ == "__main__":
    pts = points()
    ok = verify(pts)
    if "--verify" in sys.argv:
        sys.exit(0 if ok else 1)
    if not ok:
        sys.exit("refusing to write a data file that fails its own orientation check")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("# Khadi — globe land grid. GENERATED by spike/globe-land.py.\n")
        f.write("# Source: eDEX-UI src/assets/misc/grid.json (GPL-3.0), the tile set\n")
        f.write("# encom-globe draws its continents from. One 'lat lon' per line,\n")
        f.write("# degrees, geographic frame solved for in the generator.\n")
        for la, lo in pts:
            f.write(f"{la} {lo}\n")
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(pts)} points, {OUT.stat().st_size // 1024} KB)")
