//! khadi-bar — the Wayland layer-shell panel.
//!
//! This surface exists for the two motifs a cell grid cannot draw:
//!
//!   * the FAITHFUL bracket tick — `::before`/`::after` strokes hanging below
//!     a hairline rule. In a terminal that costs a whole row, which Phase 0
//!     measured at 43% of screen height across nine headers; here it is
//!     sub-pixel decoration, exactly as eDEX had it.
//!   * the ANGLED TAB BAR — `transform: skewX(35deg)` with the label skewed
//!     back. A cell grid cannot skew at all.
//!
//! Everything else it shows (clock, CPU, memory, network) duplicates what
//! khadi-hud already draws, and is here because eDEX's chrome runs along the
//! top of the screen, not because the data had nowhere else to go.

mod tabs;

use anyhow::Result;
use gtk4::{gdk, glib, prelude::*, Application, ApplicationWindow, CssProvider, Label, Orientation};
use gtk4_layer_shell::{Edge, Layer, LayerShell};
use khadi_core::{disks::Filesystem, hypr, metrics::Metrics, net::Network, Theme};
use std::{cell::RefCell, path::PathBuf, rc::Rc, time::Duration};

const APP_ID: &str = "org.khadi.bar";

/// Stylesheet path. Generated by khadi-theme like every other config, so the
/// bar cannot drift from the palette the rest of the system uses.
fn css_path() -> PathBuf {
    let base = std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .unwrap_or_else(|_| {
            PathBuf::from(std::env::var("HOME").unwrap_or_default()).join(".config")
        });
    base.join("khadi").join("bar.css")
}

fn load_css() {
    let provider = CssProvider::new();
    let p = css_path();
    if p.is_file() {
        provider.load_from_path(&p);
    } else {
        eprintln!("khadi-bar: no stylesheet at {} — run: khadi-theme build <name>", p.display());
    }
    if let Some(display) = gdk::Display::default() {
        gtk4::style_context_add_provider_for_display(
            &display,
            &provider,
            gtk4::STYLE_PROVIDER_PRIORITY_APPLICATION,
        );
    }
}

/// A label pair: an uppercase key with its value, the unit eDEX's info rows
/// are built from.
fn cell(class: &str, text: &str) -> Label {
    let l = Label::new(Some(text));
    l.add_css_class(class);
    l
}

fn build(app: &Application) {
    let window = ApplicationWindow::builder()
        .application(app)
        .default_height(28)
        .build();

    // Layer shell: a panel, not a window. `Top` keeps it above tiled clients;
    // the exclusive zone makes the compositor reserve the strip so windows do
    // not sit underneath it.
    window.init_layer_shell();
    window.set_layer(Layer::Top);
    window.set_namespace(Some("khadi-bar"));
    for (edge, on) in [
        (Edge::Top, true),
        (Edge::Left, true),
        (Edge::Right, true),
        (Edge::Bottom, false),
    ] {
        window.set_anchor(edge, on);
    }
    // The exclusive zone makes the compositor reserve the strip. That is right
    // in a Khadi session and wrong when testing on a desktop that already has
    // a bar, because it reshuffles every window on screen. KHADI_BAR_OVERLAY=1
    // floats it instead, which tests rendering without rearranging anything.
    if std::env::var("KHADI_BAR_OVERLAY").is_ok() {
        window.set_layer(Layer::Overlay);
        window.set_exclusive_zone(0);
    } else {
        window.auto_exclusive_zone_enable();
    }

    let root = gtk4::CenterBox::new();
    root.add_css_class("bar");

    // Left: the PANEL label and the skewed tab strip.
    let left = gtk4::Box::new(Orientation::Horizontal, 0);
    left.append(&cell("label", "PANEL"));
    let tabs = tabs::TabStrip::new();
    left.append(tabs.widget());
    root.set_start_widget(Some(&left));

    // Centre: the clock, in the display face.
    let clock = cell("clock", "--:--");
    root.set_center_widget(Some(&clock));

    // Right: readouts and the SYSTEM label.
    let right = gtk4::Box::new(Orientation::Horizontal, 0);
    let cpu = cell("stat", "CPU   —");
    let mem = cell("stat", "MEM   —");
    let net = cell("stat", "NET   —");
    let disk = cell("stat", "DISK  —");
    for w in [&cpu, &mem, &net, &disk] {
        right.append(w);
    }
    right.append(&cell("label", "SYSTEM"));
    root.set_end_widget(Some(&right));

    window.set_child(Some(&root));
    window.present();

    // Workspace tabs. The watcher blocks on Hyprland's event socket in its own
    // thread and publishes the newest snapshot; this timer collects it. The
    // interval bounds how late a tab can be, not how often anything is asked:
    // an idle session does one mutex lock per tick and no IPC at all.
    if hypr::available() {
        let watcher = hypr::Watcher::spawn();
        glib::timeout_add_local(Duration::from_millis(100), move || {
            if let Some(snap) = watcher.take() {
                tabs.apply(&snap);
            }
            glib::ControlFlow::Continue
        });
    } else {
        // Running on another compositor — the bar still renders, the tabs just
        // cannot mean anything.
        eprintln!("khadi-bar: no Hyprland session — workspace tabs are static");
    }

    // One timer, one refresh. khadi-core is the same code khadi-hud uses, so
    // the bar and the panels can never disagree about what the machine is
    // doing.
    let state = Rc::new(RefCell::new((Metrics::new(), Network::new(), Filesystem::new())));
    state.borrow_mut().0.refresh();
    state.borrow_mut().1.refresh();
    state.borrow_mut().2.refresh();

    glib::timeout_add_seconds_local(1, move || {
        let mut s = state.borrow_mut();
        let (m, n, fsys) = &mut *s;
        m.refresh();
        n.refresh();
        fsys.refresh();

        clock.set_text(&chrono::Local::now().format("%H:%M").to_string());
        cpu.set_text(&format!("CPU {:>3.0}%", m.cpu_avg()));
        let memp = if m.memory.total == 0 {
            0.0
        } else {
            m.memory.used as f64 / m.memory.total as f64 * 100.0
        };
        mem.set_text(&format!("MEM {memp:>3.0}%"));
        net.set_text(&format!("NET {}", khadi_core::net::rate(n.rx_rate)));
        let root_pct = fsys
            .mounts
            .iter()
            .find(|mt| mt.path == "/")
            .map(|mt| mt.frac() * 100.0)
            .unwrap_or(0.0);
        disk.set_text(&format!("DISK {root_pct:>3.0}%"));
        glib::ControlFlow::Continue
    });
}

fn main() -> Result<()> {
    // Fail early and loudly if the theme is missing: a bar that starts with no
    // stylesheet renders as default GTK, which looks like a styling bug rather
    // than a missing file.
    let theme = Theme::load()?;
    eprintln!("khadi-bar: theme {}", theme.name);

    let app = Application::builder().application_id(APP_ID).build();
    app.connect_startup(|_| load_css());
    app.connect_activate(build);
    app.run_with_args::<&str>(&[]);
    Ok(())
}
