# GENERATED by khadi-theme from themes/tron.toml — edit templates/khadi/shell.zsh.tmpl, not this file.
# Khadi — the interactive zsh layer.
#
# Sourced from a marked block in ~/.zshrc, the same way the prompt is, so your
# own rc stays yours and `khadi-install --uninstall` can take this back out.
#
# WHAT THIS IS NOT: a prompt. Khadi's prompt is starship, configured from
# themes/*.toml like every other surface, and it is appended separately. If
# you run powerlevel10k, keep it — set ZSH_THEME and this file will not fight
# you, because nothing here touches PS1.
#
# Everything below degrades: a missing package leaves the feature off rather
# than printing an error on every shell start. Khadi does not install
# packages, so each of these may be absent now or removed later.

# ------------------------------------------------------------------ history
# Shared across every pane of the session, because the whole desktop is panes.
# `hist_verify` is the important one: a recalled `!!` is put on the line for
# you to look at instead of being run.
HISTFILE="${HISTFILE:-$HOME/.zsh_history}"
HISTSIZE=32768
SAVEHIST=$HISTSIZE
setopt append_history share_history extended_history
setopt hist_ignore_dups hist_ignore_space hist_reduce_blanks hist_verify
setopt interactive_comments

# --------------------------------------------------------------- completion
# `menu_complete` is deliberate: Tab inserts the first match rather than only
# listing, which is what makes completion feel like an answer instead of a
# suggestion. Case-insensitive, then partial-word, then substring.
autoload -Uz compinit
# Once a day, not on every shell. compinit stats every file in $fpath.
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh+24) ]]; then
    compinit
else
    compinit -C
fi
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*:descriptions' format '%F{244}%d%f'
setopt complete_in_word always_to_end

# -------------------------------------------------------------- suggestions
# The grey ghost text from your history, accepted with →. The highlight is a
# theme colour rather than the default grey, so it sits in the palette.
for _k in /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh \
          /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh; do
    [[ -r $_k ]] && { source "$_k"; break; }
done
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#586c6f"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

# ------------------------------------------------------------------- search
# fzf for history (Ctrl+R) and files (Ctrl+T), themed off the same ramp the
# panels use so a popup does not arrive in somebody else's colours.
if command -v fzf >/dev/null; then
    export FZF_DEFAULT_OPTS="\
--color=fg:#89a7aa,fg+:#aacfd1\
,bg:-1,bg+:#263034\
,hl:#aacfd1,hl+:#aacfd1\
,info:#586c6f,border:#364448\
,prompt:#89a7aa,pointer:#aacfd1\
,marker:#aacfd1,spinner:#586c6f,header:#586c6f \
--height=40% --layout=reverse --border=none"
    if fzf --zsh >/dev/null 2>&1; then
        source <(fzf --zsh)
    else
        [[ -r /usr/share/fzf/completion.zsh   ]] && source /usr/share/fzf/completion.zsh
        [[ -r /usr/share/fzf/key-bindings.zsh ]] && source /usr/share/fzf/key-bindings.zsh
    fi
fi

command -v zoxide >/dev/null && eval "$(zoxide init zsh)"

# ------------------------------------------------------------------- keys
# Emacs bindings, and the two everyone reaches for that zsh does not bind.
bindkey -e
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^[[3~'   delete-char
bindkey '^[[H'    beginning-of-line
bindkey '^[[F'    end-of-line

# --------------------------------------------------------------- highlight
# LAST, and that is not a style point: zsh-syntax-highlighting wraps the
# widgets everything above defines, so anything sourced after it is not
# highlighted. Its own README says so in capitals.
for _k in /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh \
          /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh; do
    [[ -r $_k ]] && { source "$_k"; break; }
done
unset _k
typeset -gA ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[comment]='fg=#47585b'
ZSH_HIGHLIGHT_STYLES[command]='fg=#aacfd1'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#aacfd1'
ZSH_HIGHLIGHT_STYLES[function]='fg=#aacfd1'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#aacfd1'
ZSH_HIGHLIGHT_STYLES[path]='fg=#89a7aa'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#687f83'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#687f83'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#586c6f,underline'
