//! The spinning globe.
//!
//! eDEX's WORLD VIEW is encom-globe: WebGL, Three.js, 975 KB of JavaScript.
//! A cell grid cannot render WebGL at any price — but the thing that actually
//! reads on screen is not the shading, it is **a dotted sphere turning**, and
//! a braille canvas has 2x4 subpixels per cell to spend on exactly that.
//!
//! The land is eDEX's own grid, not an approximation of it: 3937 tiles from
//! `src/assets/misc/grid.json`, the set encom-globe draws its continents from.
//! Khadi is GPL-3.0 and so is eDEX, so the authentic data is available.
//!
//! What is still deliberately absent is geolocation. eDEX pinned connection
//! endpoints resolved through MaxMind; GeoLite2 needs an account and carries
//! redistribution terms an ISO should not take on, so this globe shows the
//! world without claiming to know where anyone is.

use khadi_core::Theme;
use ratatui::{
    buffer::Buffer,
    layout::Rect,
    symbols::Marker,
    widgets::{
        canvas::{Canvas, Circle, Points},
        Widget,
    },
};
use std::sync::OnceLock;

use crate::widgets::col;

/// GENERATED by `spike/globe-land.py` from the eDEX clone. Embedded rather
/// than read at runtime: a panel that needs a data file beside it is a panel
/// that breaks when someone copies the binary.
const LAND_SRC: &str = include_str!("globe/land.txt");

/// Degrees per second. One turn a minute — fast enough to read as alive,
/// slow enough that a panel in the corner of the eye is not a distraction.
pub const DEG_PER_SEC: f64 = 6.0;

/// Target spacing between land dots, in braille subpixels.
///
/// eDEX's globe is a DOT MATRIX, not a filled shell — the gaps are what make
/// it read as a grid wrapped on a sphere rather than a silhouette. The source
/// grid is about 1.6 subpixels apart on a 34-column panel, which braille
/// renders as solid, so the points have to be thinned.
///
/// NOT BY QUANTISING TO A LATTICE. That was tried: the land grid is itself a
/// ~3.6° mesh, and snapping one grid onto another aliases into moiré stripes
/// that read as a defect. The thinning is a stable hash per point instead —
/// no lattice, so nothing to beat against, and deterministic so the pattern
/// does not shimmer as the globe turns.
const DOT_SPACING: f64 = 1.8;

/// How much taller than wide a braille subpixel is.
///
/// Braille packs 2 subpixels across a cell and 4 down, so a subpixel is square
/// only if the cell is exactly 2:1. Iosevka Term has a 0.5 em advance (PLAN.md
/// section 3) and foot's line height puts the cell nearer 2.75:1 — which makes
/// a subpixel 1 : 1.375, and a sphere drawn as if they were square comes out
/// an egg. Measured on the reference layout before this was applied: the globe
/// read 0.72 as wide as it was tall.
///
/// The canvas is therefore scaled in SUBPIXEL WIDTHS on both axes, so a circle
/// is a circle and `Circle` can be used for the limb instead of a hand-rolled
/// ellipse. Tied to the locked mono font; a theme that changes it changes this.
const SUBPIXEL_ASPECT: f64 = 1.375;

/// Axial tilt toward the viewer. Dead-on, the poles sit exactly on the limb
/// and the sphere reads as a flat disc; tilted, the top of the globe curves
/// away and the eye gets the roundness for free.
const TILT_DEG: f64 = 23.5;

fn land() -> &'static [(f64, f64)] {
    static LAND: OnceLock<Vec<(f64, f64)>> = OnceLock::new();
    LAND.get_or_init(|| {
        LAND_SRC
            .lines()
            .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
            .filter_map(|l| {
                let (lat, lon) = l.split_once(' ')?;
                Some((lat.trim().parse().ok()?, lon.trim().parse().ok()?))
            })
            .collect()
    })
}

/// Stable per-point thinning. Keyed on the coordinates rather than on an
/// index, so the same dots survive at every rotation and the pattern holds
/// still while the globe moves under it.
fn keep(lat: f64, lon: f64, frac: f64) -> bool {
    let k = ((lat * 100.0) as i64).wrapping_mul(73_856_093)
        ^ ((lon * 100.0) as i64).wrapping_mul(19_349_663);
    (k.unsigned_abs() % 10_000) as f64 <= frac * 10_000.0
}

pub struct Globe<'a> {
    pub theme: &'a Theme,
    /// Rotation in degrees. The caller owns the clock so that `--once` can
    /// render a fixed frame and the test suite can pin an angle.
    pub spin: f64,
}

impl Globe<'_> {
    /// Project the land onto the sphere, split into three depth bands.
    ///
    /// Returned in canvas coordinates, which this widget defines as braille
    /// subpixels: 2 per column, 4 per row. That makes them square, so a
    /// sphere comes out round instead of egg-shaped — the thing a canvas
    /// scaled in degrees of longitude gets wrong.
    fn project(&self, area: Rect) -> Projection {
        let (sx, sy) = Self::canvas(area);
        let r = sx.min(sy) / 2.0 * 0.92;
        let (cx, cy) = (sx / 2.0, sy / 2.0);

        let (st, ct) = TILT_DEG.to_radians().sin_cos();
        let spin = self.spin.to_radians();
        let mut bands: [Vec<(f64, f64)>; 3] = Default::default();

        // How many dots the disc has room for at the target spacing, against
        // how many would otherwise land on it. Roughly half the grid faces us
        // at any moment. Scaling this to the radius rather than fixing a count
        // is what keeps the texture the same in a 9-row panel and a 20-row one.
        let room = std::f64::consts::PI * r * r / (DOT_SPACING * DOT_SPACING);
        let frac = (room / (land().len() as f64 / 2.0)).clamp(0.05, 1.0);

        for &(lat, lon) in land() {
            if !keep(lat, lon, frac) {
                continue;
            }
            let (slat, clat) = lat.to_radians().sin_cos();
            let (slon, clon) = (lon.to_radians() + spin).sin_cos();
            // Unit sphere with Y polar, which is the frame the eDEX tiles are
            // in once their 3D centres are read instead of their lat/lon
            // fields. See spike/globe-land.py.
            let (x, y, z) = (clat * slon, slat, clat * clon);
            // Tilt about X, bringing the north pole toward the viewer.
            let (y, z) = (y * ct - z * st, y * st + z * ct);
            if z <= 0.0 {
                continue; // far side; the sphere is opaque
            }
            let band = if z > 0.66 {
                0
            } else if z > 0.33 {
                1
            } else {
                2
            };
            bands[band].push((cx + x * r, cy + y * r));
        }
        Projection { bands, cx, cy, r, sx, sy }
    }

    /// Canvas extent in SUBPIXEL WIDTHS — the unit that makes both axes
    /// isotropic, so round things come out round.
    fn canvas(area: Rect) -> (f64, f64) {
        (
            area.width as f64 * 2.0,
            area.height as f64 * 4.0 * SUBPIXEL_ASPECT,
        )
    }
}

struct Projection {
    /// Land dots, back to front.
    bands: [Vec<(f64, f64)>; 3],
    cx: f64,
    cy: f64,
    r: f64,
    sx: f64,
    sy: f64,
}

impl Widget for Globe<'_> {
    fn render(self, area: Rect, buf: &mut Buffer) {
        // Below this there are not enough subpixels for a sphere to read as
        // one, and a four-pixel blob is worse than nothing.
        if area.width < 8 || area.height < 3 {
            return;
        }
        let t = self.theme;
        let Projection { bands, cx, cy, r, sx, sy } = self.project(area);

        Canvas::default()
            .marker(Marker::Braille)
            .x_bounds([0.0, sx])
            .y_bounds([0.0, sy])
            .paint(|ctx| {
                // The limb first. Without it the Pacific face is nearly empty
                // and the land reads as blobs floating in the dark rather than
                // as the near side of something round.
                ctx.draw(&Circle { x: cx, y: cy, radius: r, color: col(t.a(30)) });
                ctx.layer();
                // Back to front, dim to bright: the depth cue that makes a
                // flat dot field look spherical.
                for (band, shade) in [(2, t.a(40)), (1, t.a(70)), (0, t.text)] {
                    ctx.draw(&Points { coords: &bands[band], color: col(shade) });
                    ctx.layer();
                }
            })
            .render(area, buf);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use khadi_core::Theme;

    fn theme() -> Theme {
        Theme::from_str(include_str!("../../../config/khadi/theme.toml")).unwrap()
    }

    #[test]
    fn the_land_grid_parses() {
        let l = land();
        assert_eq!(l.len(), 3937, "every eDEX tile should survive the parse");
        assert!(l.iter().all(|&(lat, lon)| (-90.0..=90.0).contains(&lat)
                                        && (-180.0..=180.0).contains(&lon)));
    }

    /// The point of reading the tiles' 3D centres instead of their lat/lon
    /// fields: taken at face value those put land in the Indian Ocean and
    /// none in Antarctica. This pins the frame the generator solved for.
    #[test]
    fn the_land_is_where_land_is() {
        let near = |la: f64, lo: f64| {
            land().iter().any(|&(a, b)| (a - la).abs() < 7.0
                && (((b - lo + 180.0).rem_euclid(360.0)) - 180.0).abs() < 7.0)
        };
        for (la, lo, name) in [(-5.0, -62.0, "Amazon"), (22.0, 10.0, "Sahara"),
                               (-25.0, 134.0, "Australia"), (40.0, -100.0, "US")] {
            assert!(near(la, lo), "{name} should be land");
        }
        for (la, lo, name) in [(0.0, -140.0, "mid-Pacific"), (-20.0, 80.0, "Indian Ocean"),
                               (30.0, -40.0, "N.Atlantic")] {
            assert!(!near(la, lo), "{name} should be ocean");
        }
    }

    #[test]
    fn every_point_lands_inside_the_disc() {
        let t = theme();
        let area = Rect::new(0, 0, 34, 14);
        let g = Globe { theme: &t, spin: 123.0 };
        let Projection { bands, cx, cy, r, .. } = g.project(area);
        let n: usize = bands.iter().map(Vec::len).sum();
        assert!(n > 150, "expected a populated hemisphere, got {n}");
        assert!(n < land().len(), "nothing was thinned: {n} of {}", land().len());
        for p in bands.iter().flatten() {
            let d = ((p.0 - cx).powi(2) + (p.1 - cy).powi(2)).sqrt();
            assert!(d <= r + 1e-6, "point {p:?} escaped the limb (r={r})");
        }
    }

    /// Half the planet is behind the planet.
    #[test]
    fn the_far_side_is_hidden() {
        let t = theme();
        let area = Rect::new(0, 0, 34, 14);
        let bands = Globe { theme: &t, spin: 0.0 }.project(area).bands;
        let shown: usize = bands.iter().map(Vec::len).sum();
        assert!(shown < land().len(), "nothing was culled — the sphere is transparent");
        assert!(shown > land().len() / 8, "too much culled: {shown} of {}", land().len());
    }

    /// Projection changing is not the same as the screen changing: the dots
    /// could all land back on the same braille cells. This is the one that
    /// says a viewer would see motion.
    #[test]
    fn the_rendered_frame_changes_as_it_turns() {
        let t = theme();
        let area = Rect::new(0, 0, 34, 14);
        let mut a = Buffer::empty(area);
        let mut b = Buffer::empty(area);
        Globe { theme: &t, spin: 0.0 }.render(area, &mut a);
        Globe { theme: &t, spin: 60.0 }.render(area, &mut b);
        assert_ne!(a, b, "a sixth of a turn redrew the same frame");
    }

    /// It shipped as an egg once. A cell is about 2.75 times taller than it
    /// is wide, so a round globe has to span about 2.75 times more COLUMNS
    /// than rows; drawn as if braille subpixels were square it came out 0.72
    /// as wide as tall. This measures the rendered bounding box, which is the
    /// thing a viewer actually sees.
    #[test]
    fn it_is_round_rather_than_an_egg() {
        let t = theme();
        let area = Rect::new(0, 0, 40, 16);
        let mut buf = Buffer::empty(area);
        Globe { theme: &t, spin: 0.0 }.render(area, &mut buf);

        let (mut x0, mut x1, mut y0, mut y1) = (u16::MAX, 0u16, u16::MAX, 0u16);
        for y in 0..area.height {
            for x in 0..area.width {
                if buf[(x, y)].symbol().trim().is_empty() {
                    continue;
                }
                x0 = x0.min(x); x1 = x1.max(x);
                y0 = y0.min(y); y1 = y1.max(y);
            }
        }
        let (w, h) = ((x1 - x0 + 1) as f64, (y1 - y0 + 1) as f64);
        let want = 2.0 * SUBPIXEL_ASPECT;
        assert!((w / h - want).abs() < 0.45,
                "globe spans {w}x{h} cells, ratio {:.2}, wanted about {want:.2}", w / h);
    }

    #[test]
    fn it_actually_turns() {
        let t = theme();
        let area = Rect::new(0, 0, 34, 14);
        let a = Globe { theme: &t, spin: 0.0 }.project(area).bands;
        let b = Globe { theme: &t, spin: 90.0 }.project(area).bands;
        assert_ne!(a[0], b[0], "a quarter turn changed nothing");
    }

    /// The side panel is 34 columns and the globe shares it with six other
    /// readouts, so it has to survive whatever height is left.
    #[test]
    fn it_survives_every_size_it_can_be_given() {
        let t = theme();
        for w in 1u16..=40 {
            for h in 1u16..=20 {
                let mut buf = Buffer::empty(Rect::new(0, 0, w, h));
                Globe { theme: &t, spin: 37.0 }.render(Rect::new(0, 0, w, h), &mut buf);
            }
        }
    }
}
